update compat
JuliaSmoothOptimizers/RegularizedProblems.jl pull request #41
Opened 2023-06-05 18:36 UTC by dpo

2023-06-06 14:27 UTC, dpo commented
@tmigot There is an issue with the sparse Hessian backend here: https://github.com/JuliaSmoothOptimizers/RegularizedProblems.jl/actions/runs/5180679050/jobs/9335162380#step:6:694. Could you please have a look when you have a moment?

2023-08-14 11:00 UTC, tmigot commented
Is this still an issue with the last release of ADNLPModels 0.6 or the version 0.7 ?

2023-08-21 14:43 UTC, geoffroyleconte requested changes

2023-08-21 14:43 UTC, geoffroyleconte commented on Project.toml
> +ADNLPModels = "^0.3, 0.4, 0.5, 0.6"
```suggestion
ADNLPModels = "^0.3, 0.4, 0.7"
```
@dpo this works locally for me

2024-02-20 18:18 UTC, merged